export const imagesDark = {
  jangou_bertikala: require('./bertikala_dark.png'),
  jangou_horizontala: require('./horizontala_dark.png'),
  instagram: require('./instagram.png'),
  facebook: require('./facebook.png'),
  telegram: require('./telegram.png'),
  twitter: require('./twitter.png'),
  whatsapp: require('./whatsapp.png'),
  skura: require('./skura_dark.png'),
  default: require('./default.jpg'),
  phone: require('./phone.png'),
  navigate: require('./navigate.png'),
  share: require('./share.png'),
  warning: require('./warning.png'),
  globe: require('./globe.png'),
  mail: require('./mail.png'),
  iconlocation: require('./IconLocation.png'),
};

export const imagesLight = {
  jangou_bertikala: require('./bertikala_light.png'),
  jangou_horizontala: require('./horizontala_light.png'),
  instagram: require('./instagram.png'),
  facebook: require('./facebook.png'),
  telegram: require('./telegram.png'),
  twitter: require('./twitter.png'),
  whatsapp: require('./whatsapp.png'),
  skura: require('./skura_light.png'),
  default: require('./default.jpg'),
  phone: require('./phone.png'),
  navigate: require('./navigate.png'),
  share: require('./share.png'),
  warning: require('./warning.png'),
  globe: require('./globe.png'),
  mail: require('./mail.png'),
  iconlocation: require('./IconLocation.png'),
};
